NutritionApp/Models/ErrorViewModel.cs
namespace NutritionApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NutritionApp/Models/Ingredient.cs
namespace NutritionApp.Models
{
    public class Ingredient
    {
        public int IngredientId { get; set; }
        public string Name { get; set; }
        public int Amount { get; set; } //this is amount in oz
        public int Calories { get; set; }
        public int Carbs { get; set; }
        public int Protein { get; set; }
        public int Fiber { get; set; }
        public int Fat { get; set; }
    }
}

NutritionApp/Models/Recipe.cs
namespace NutritionApp.Models
{
    public class Recipe
    {
        public int RecipeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Instructions { get; set; }

    }
}

NutritionApp/Models/RecipeIngredient.cs
namespace NutritionApp.Models
{
    public class RecipeIngredient
    {
        public int RecipeIngredientId { get; set; }
        public int IngredientId { get; set; }
        public int RecipeId { get; set; }
    }
}

NutritionApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NutritionApp.Models;
using System.Diagnostics;
using System.Xml.Linq;

namespace NutritionApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        IRecipeRepository repo;

        public HomeController(ILogger<HomeController> logger, IRecipeRepository r)
        {
            _logger = logger;
            repo = r;
        }

        public IActionResult Index(List<Recipe> recipes)
        {
            return View(recipes);
        }

        [HttpPost]
        public IActionResult Index(string toname)
        {
            List<Recipe> recipes = new();
            if (!(string.IsNullOrEmpty(toname))) 
                recipes = repo.GetRecipes().Where(p => p.Name == toname).ToList();

            return View("Index", recipes);
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NutritionApp/Controllers/IngredientController.cs
using Microsoft.AspNetCore.Mvc;
using NutritionApp.Data;
using NutritionApp.Models;

namespace NutritionApp.Controllers
{
    public class IngredientController : Controller
    {
        IIngredientRepository repo;
        List<int> recipeIngredients = new List<int>();
        public IngredientController(IIngredientRepository r)
        {
            repo = r;
        }
        public IActionResult Index(List<Ingredient> ingredients)
        {
            return View(ingredients);
        }

        [HttpPost]
        public IActionResult Index(string toname, string ingr)
        {
            List<Ingredient> ingredients = new();
            Ingredient i;
            if (toname == null)
                ingredients = repo.GetIngredients().ToList();
            else
                ingredients = repo.GetIngredients().Where(p => p.Name == toname).ToList();
            if (ingr != null)
            {
                i = repo.GetIngredientById(int.Parse(ingr));
                return RedirectToAction("ConfirmIngredient", i);
            }

            return View("Index", ingredients);
        }

        public IActionResult ConfirmIngredient(Ingredient i)
        {
            return View(i);  
        }

        [HttpPost]
        public IActionResult ConfirmIngredient(string yesno, Ingredient i)
        {
            if (yesno == "Yes")
                return RedirectToAction("AddRecipe", "Recipe", i);
            else 
                return RedirectToAction("Index");
        }
        public IActionResult AddIngredient()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddIngredient(Ingredient model)
        {
            // Save model to db
            repo.StoreIngredient(model);

            return RedirectToAction("Index");
        }
    }
}

NutritionApp/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Mvc;
using NutritionApp.Data;
using NutritionApp.Models;

namespace NutritionApp.Controllers
{
    public class RecipeController : Controller
    {
        IRecipeRepository repo;
        IIngredientRepository ingredientRepository;
        IRecipeIngredientRepository ingrRepo;

        public RecipeController(IRecipeRepository r, IIngredientRepository inRepo, IRecipeIngredientRepository ir)
        {
            repo = r;
            ingredientRepository = inRepo;
            ingrRepo = ir;
        }
        public IActionResult Index(List<Recipe> recipes)
        {
            return View(recipes);
        }

        [HttpPost]
        public IActionResult Index(string toname)
        {
            List<Recipe> recipes = repo.GetRecipes().Where(p => p.Name == toname).ToList();

            return View("Index", recipes);
        }


        public IActionResult AddRecipe(Ingredient i)
        {
            List<Ingredient> ingredients = new();
            Recipe recipe = new();

            RecipeIngredient ing = new();
            // On first load, i will be null, but other times it will have something in it
            if (i.Name != null)
            {
                /*ingredients.Add(i);*/
/*                repo.StoreRecipe(recipe);
*/              ing.IngredientId = i.IngredientId;
                ing.RecipeId = recipe.RecipeId;
                ingrRepo.StoreRecipeIngredient(ing);

                List<RecipeIngredient> ingrs = ingrRepo.GetRecipeIngredients().Where(p => p.RecipeId == recipe.RecipeId).ToList();
                foreach(var recipeIngr in ingrs)
                {
                    ingredients.Add(ingredientRepository.GetIngredientById(recipeIngr.IngredientId));
                }
            }
            
            // The view wants a list of ingredients to display
            return View(ingredients);
        }

        [HttpPost]
        public IActionResult AddRecipe(Recipe model)
        {
            // Save model to db
            repo.StoreRecipe(model);

            return RedirectToAction("AddRecipe");
        }
    }
}

NutritionApp/Views/Home/About.cshtml
<p>This website is designed to help you create meal plans that work for you! With high levels of recipe customization, the kitchen is yours to prepare tasty, healthy, or whatever you desire.</p>

<p>Already know which recipes you love? Search them by Id. Simply type the number into the search bar at the top left corner of the screen.</p>

<p>Found a new recipe that you want to add? Try the "Add Recipe" tab at the top, right next to the search bar. There you can add in your favorite recipes to your list. Don't forget to click submit when you are done to save your recipe!'</p>

<p>If you can't find on of the ingredients needed for your recipe, that's okay too! Just click the + icon next to the "ingredients" portion of the new Recipe form, and from there you can add a new ingredient to your pantry. You only need to add an ingredient's information one time. For the next time, the information will be saved and ready to add to your recipe from the ingredient search bar.</p>

<p>Don't know what you want to make? That's okay too! Browse the FYP (For You Page) to see which recipe we recommend. If you aren't interested in any of those recipe, just refresh the page for a new set of tasty treats!'</p>

NutritionApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

</div>

NutritionApp/Views/Ingredient/AddIngredient.cshtml
@model Ingredient

<form method="post" class="container-fluid">
    <div class="row b">
        <div class="col-12 b">
            <label for="ingredientName">Ingredient Name</label><br />
            <input id="ingredientName" name="Name" type="text" />
        </div>
    </div>
    <div class="row b">
        <div class="col-12 b">
            <label for="amount">Amount (oz)</label><br />
            <input id="amount" name="Amount" type="number" />
        </div>
    </div>
    <div class="row b">
        <div class="col-12 b">
            <label for="calories">Calories</label><br />
            <input id="calories" name="Calories" type="number" />
        </div>
    </div>
    <div class="row b">
        <div class="col-12 b">
            <label for="carbs">Carbs</label><br />
            <input id="carbs" name="Carbs" type="number" />
        </div>
    </div>
    <div class="row b">
        <div class="col-12 b">
            <label for="protein">Protein</label><br />
            <input id="protein" name="Protein" type="number" />
        </div>
    </div>
    <div class="row b">
        <div class="col-12 b">
            <label for="fiber">Fiber</label><br />
            <input id="fiber" name="Fiber" type="number" />
        </div>
    </div>
    <div class="row b">
        <div class="col-22 b">
            <label for="fat">Fat</label><br />
            <input id="fat" name="Fat" type="number" />
        </div>
    </div>
    <div class="row b">
        <div class="col-12 b">
            <input type="submit" value="save" />
        </div>
    </div>
</form>

NutritionApp/Views/Ingredient/ConfirmIngredient.cshtml
@model Ingredient

<form method="post">   
    Would you like to add @Model.Name to your recipe?   
    <input type="submit" name="yesno" value="Yes"/>
    <input type="submit" name="yesno" value="No" />
</form>

NutritionApp/Views/Ingredient/Index.cshtml
@model List<Ingredient>

<form method="post">
    <input name="toname" />
    <input type="submit" value="Find Ingredients"/>
</form>
<h1>Ingredients</h1>
@if (@Model != null)
{
    @foreach (var ingr in Model)
    {
        <form method="post">
            <input name="ingr" value="@ingr.IngredientId" />
            <input type="submit" value="+" />
            Name: @ingr.Name
        </form>
        @* <div>
            <a class="text-dark" asp-area="" asp-controller="Ingredient" asp-action="ConfirmIngredient">+</a>
            Name: @ingr.Name
        </div> *@
    }
}

NutritionApp/Views/Recipe/AddRecipe.cshtml
@model List<Ingredient>

<form method="post" class="container-fluid">
    <div class="row b">
        <div class="col-2 b">
            <label for="recipeName">Recipe Name</label><br />
            <input id="recipeName" name="Name" type="text" />
        </div>
        <div class="col-5 b">
            <div class="row b">
                <div class="col-6 b">
                    <a class="text-dark" asp-area="" asp-controller="Ingredient" asp-action="AddIngredient">Create New Ingredient</a>
                </div>
                <div class="col-2 b">
                    <a class="btn btn-secondary" asp-area="" asp-controller="Ingredient" asp-action="Index">+</a>
                </div>
                <div class="col-3 b">
                    Amount (oz)
                </div>
            </div>
        </div>
        <div class="col-5 b">
            <label for="instructions">Instructions</label>
        </div>
    </div>
    <div class="row b">
        <div class="col-2 b">
            <label for="description">Description</label><br />
            <input id="description" name="Description" type="text" class="descriptionBox" />
        </div>
        <div class="col-5 b">
            @if (@Model != null)
            {
                @foreach (var ingr in Model)
                {
                    <div id="@ingr.IngredientId" class="row b">
                        <div class="col-2 b">
                        <input type="button" value="-" />
                        </div>
                        <div class="col-6 b">
                        <input type="text" readonly value="@ingr.Name"/>
                        </div>
                        <div class="col-4 b">
                        <input type="number" class="numberInput" />
                        </div>
                    </div>
                }
            }
        </div>
        <div class="col-5 b">
            <input id="instructions" name="Instructions" type="text" class="descriptionBox" />
        </div>
    </div>
    <div class="row b">
        <div class="col-3 b">
            <input type="submit" value="save" />
        </div>
    </div>
</form>

NutritionApp/Views/Recipe/Index.cshtml
@model List<Recipe>

@{
    ViewData["Title"] = "Blog Home";
}
<h2>Filter Recipes</h2>
<form method="post">
    <label>Recipe Name</label>
    <input name="toname" />
    <input type="submit" />
</form>
<h1>Recipes</h1>
@if (@Model != null)
{

    @foreach (var recipe in Model)
    {
        <p>
            Name: @recipe.Name <br>
            Description: @recipe.Description <br>
            Instructions: @recipe.Instructions <br>
        </p>
    }
}

NutritionApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NutritionApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NutritionApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NutritionApp</a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <form method="post">
                                <input type="text" value="Search" name="toname"/>
                            </form>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="AddRecipe">Add Recipe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipe" asp-action="Index">FYP</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @model List<Recipe>

        @if (@Model != null)
        {

            @foreach (var recipe in Model)
            {
                <p>
                    Name: @recipe.Name <br>
                    Description: @recipe.Description <br>
                    Instructions: @recipe.Instructions <br>
                </p>
            }
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NutritionApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>